# example values

server:
  port: 8080
spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create #create-drop, create, update
    show-sql: false

indexing-settings:
  sites:
    - url: https://volochek.life #https://www.lenta.ru
      name: Volochek.Life #Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.dfhdh.ru
      name: Тест несуществующего сайта

parser-setting:
  user-agent: LocoBOT/0.0.2 (indexing and search engine) #"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36";
  referrer: https://google.ru