server:
  port: 8080
spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        generate_statistics: false
        jdbc:
          batch_size: 1000
    hibernate:
      ddl-auto: update # create-drop, create, update
    show-sql: false

indexing-settings:
  sites:
    - url: https://volochek.life
      name: Volochek.Life
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.dfhdh.ru
      name: Тест несуществующего сайта

parser-setting:
  user-agent: MG_Indexing_Bot/1.0.0 (Indexing and search engine) # "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36";
  referrer: https://google.ru
  random-delay-delta-before-connection: 2000
  min-delay-before-connection: 1000
  connection-timeout: 10000
