server:
  port: 8080
spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        generate_statistics: false
        jdbc:
          batch_size: 10000 # entities (Used in BatchIndexWriter)
    hibernate:
      ddl-auto: create # create-drop, create, update
    show-sql: false

indexing-settings:
  sites:
    - url: https://volochek.life
      name: Volochek.Life
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://www.dfhdh.ru
      name: Тест несуществующего сайта

parser-setting:
  user-agent: MG_Indexing_Bot/1.0.0 (Indexing and search engine)
  referrer: https://google.ru
  random-delay-delta-before-connection: 200 # ms
  min-delay-before-connection: 300 # ms (Connection to each page uses 1000(min-delay) + random 0-2000(delta))
  connection-timeout: 3000 # ms
  batch-size: 10000 # entities (Used in BatchIndexWriter)
  cpu-for-pool: 10 # number of processors to use by the ForkJoinPool

search-setting:
  pages-percent-for-lemma: 5 # % (The search is carried out in pages where the lemma occurs no more often than this percent)
  max-snippet-size: 280 # characters
  min-chars-count-around-word: 10 # characters (Minimum number of characters around the bolded word in snippet)

